In [13]:
# Creating ndarray

import numpy as np
import pandas as pd

data = [[1,2,3,4,5],[6,7,8,9,10]]

arr = np.array(data, dtype=np.float64)

arr # returns data as array

# arr.shape #shape of array
# arr.dtype # array data type

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

In [8]:
# Operating between arraya and scalers

arr1 = arr * arr

arr1

3 * arr


array([[  3.,   6.,   9.,  12.,  15.],
       [ 18.,  21.,  24.,  27.,  30.]])

In [3]:
# Basic Indexing and Slicing: here are many ways you may want to select a subset of your data or individual elements.

ar_01 = np.arange(10)
ar_01


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar_01[5] #element at index 5. Thats the sixth element in the array

5

In [6]:
ar_01[5:8] #element from index 5 up to the element before index 8

array([5, 6, 7])

In [8]:
#Can assign new value to all elements
ar_01[5:8] = 12
ar_01

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [9]:
#working with array slices
ar_01_slice = ar_01[5:8]
ar_01_slice[2] = 67 #assigning the element at index 2 a new value of 67

ar_01

array([ 0,  1,  2,  3,  4, 12, 12, 67,  8,  9])

In [17]:
#Working with multi dimentional arrays

arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

arr2d_DataFrame = pd.DataFrame(arr2d) #making arr2d a Dataframe using Pandas

#the elements at each index are no longer scalars but rather one-dimensional arrays

arr2d[2]


array([7, 8, 9])

In [11]:
#locating a single value
arr2d[2,0]

7

In [18]:
arr2d_DataFrame

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [21]:
#A 3d array

arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
nsteps = 1000

draws = np.random.randint(0, 2, size=nsteps)

steps = np.where(draws > 0, 1, -1)

walk = steps.cumsum()

In [29]:
walk.max()

#walk.max()

5